server:
    port: 8081
spring:
    cloud:
        config:
            server:
                # aqui tienes que cambiar sobre la rama que estas trabajando para que no haya problema
                git:
                    default-label: zipkin-sleuth
                    uri: https://github.com/LeonardMx/microservicios-tutorial
                    search-paths: config-data
    application:
        name: config-service
    
